- 👋 Hi, I’m DH or Deadheart
- I am game tester, an amateur game developer and user-expereience enthusiast.
- I’m currently learning Unity, Unreal Engine and Roblox and work around projects revolving these
